apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev
spec:
  selector:
      matchLabels:
        app: my-app
  replicas: 1
  template:
      metadata:
        labels:
            app: my-app
      spec:
        containers:
        - name: my-app
          image:  "${{ secrets.ACR_NAME }}/demo-app:latest"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8000
              path: /
          livenessProbe:
            httpGet:
              port: 8000
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
