apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Promise-Igbo/demo-app.git
  branch: main
  # secretRef:
  #   name: flux-system
