# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: my-app
#   namespace: flux-system
# spec:
#   interval: 5m
#   path: k8s
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   validation: client
  # healthChecks:
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   name: my-app
  #   namespace: default
# kustomization.yaml in the root of your GitOps repository

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/   # Path to where your resources like Namespace and Deployment are
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client


# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: arbitrary

# # Example configuration for the webserver
# # at https://github.com/monopole/hello
# commonLabels:
#   app: hello

# resources:
# - deployment.yaml
# - service.yaml