apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s  # Path to where your resources like Namespace and Deployment are (k8s/dev, k8s/stage)
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
