apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: stage
  namespace: flux-system
spec:
  resources:
    - ../../namespace.yaml  # This correctly points to the namespace.yaml in the parent directory
    - deployment-stage.yaml  # Your deployment resource for the dev namespace
    - svc.yaml  # Your service resource for the dev namespace
