name: Deploy to AKS

# When this action will be executed
on:
  push:
    branches: 
      - main
    paths:
      - 'k8s/**'   # Trigger pipeline only if changes are made in the k8s folder
      - 'cluster/**'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up kubectl for AKS
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.2'  # Specify the kubectl version

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }}

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }} 
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_NAME }}/demo-app:${{ github.sha }}, ${{ secrets.ACR_NAME }}/demo-app:latest
          file: ./Dockerfile

      # - name: Update Image Version in GitOps Repo
      #   run: |
      #     sed -i 's|image: .*$|image: ${{ secrets.ACR_NAME }}/demo-app:${{ github.sha }}|' ./k8s/dev/deployment-dev.yaml
      #     git add ./k8s/dev/deployment-dev.yaml
      #     git commit -m "Update image to ${{ github.sha }}"

      #     sed -i 's|image: .*$|image: ${{ secrets.ACR_NAME }}/demo-app:${{ github.sha }}|' ./k8s/stage/deployment-stage.yaml
      #     git add ./k8s/stage/deployment-stage.yaml
      #     git commit -m "Update image in stage to ${{ github.sha }}"

      #     git push origin main


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate with AKS
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}

      - name: Reconcile Cluster Configuration
        run: |
          flux reconcile kustomization cluster --with-source

      - name: Reconcile Dev Environment
        run: |
          flux reconcile kustomization dev --with-source

      - name: Reconcile Stage Environment
        run: |
          flux reconcile kustomization stage --with-source
