name: deploy to azure containerapp
 
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    
 
  # Allow mannually trigger 
  workflow_dispatch:      
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: wakappregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
 
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wakappregistry.azurecr.io/demo-app:${{ github.sha }} , wakappregistry.azurecr.io/demo-app:latest
          file: ./Dockerfile
          
 
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/actions/login@v1
        env:
         CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: $'{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          allow-no-subscriptions: true
 
 
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n wakappregistry -g wakanowrg --server wakappregistry.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
            az containerapp update -n wakappregistry -g wakanowrg --image wakappregistry.azurecr.io/demo-app:${{ github.sha }}
