name: Trigger auto deployment of containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
  branches:
    [ main ]
    
  # Allow manually trigger
workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout to the branch
          uses: actions/checkout@v2
          with:
            path: main
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
        - name: Login into Container Registry
          uses: docker/login-action@v1
          with:
            registry: wakappregistry.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: Build and push image into Container Registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: wakappregistry.azurecr.io/newappacr:${{ github.sha }}
            file: ./Dockerfile
            
           
 deploy
  runs-on: ubuntu-latest
  needs: build
            
  steps:          
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      
    - name: Deploy to Containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Installing containerapp extension"
          az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/connection
          echo "Start Deploying"
          az container app update -n newappacr -g wakanowrg -i wakappregistry.azurecr.io/newappacr:${{ github.sha }}
